#Composite Action = Reusable group of steps packaged as one action


name: composte_action

on: workflow_dispatch

jobs:
  composite-action-job:
    runs-on: [self-hosted, vagrant]

    steps:
      - name: Run composite action
        uses: ./.github/actions/setup-java-app
        with:
          java-version: 8
