#Composite Action = Reusable group of steps packaged as one action
#actions/setup-java sets up Java for workflow steps, not the VM globally
#Composite actions are step-level reusable units

name: composte_action

on: workflow_dispatch

jobs:
  composite-action-job:
    runs-on: [self-hosted, vagrant]

    steps:
    - name: Setup checkout
      uses: actions/checkout@v6
    - name: Run composite action
      uses: ./.github/actions/setup-java-app
      with:
        java-version: 8
