name: github-actions-poc
on:
  workflow_dispatch:

jobs:
  run-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is hello world example for github action poc"
  run-python:
    runs-on: ubuntu-latest
    steps:
      - run: print("this is example python run")
        shell: python