name: Secrets_environments
on:
  workflow_dispatch:

env:
  repo_var: ${{ secrets.EXAMPLE_REPO_VAR }}
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: print secret variable
        run: echo "repo secret variable $repo_var"