name: Secrets_environments
on:
  workflow_dispatch:

env:
  repo_var: ${{ secrets.TEST_SECRET }}
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: print secret variable
        run: echo "repo secret variable $repo_var"


# needs.job1.outputs.my_var -> outputs and values from dependent jobs
# ${{ steps.setvar.outputs.my_var }} -> this line is the bridge between a step and the job output.
# ${{ secrets.repository_secret_variables }}
# ${{ vars.repository_repo_variables }}