#same runner with different labels
name: self_hosted_runners
on:
  workflow_dispatch:

jobs:
  run-bash:
    runs-on: [self-hosted, vagrant]
    steps:
      - run: echo "this is running on self hosted runner with label of vagrant"
  run-python:
    runs-on: [self-hosted, ubuntu-focal]
    steps:
      - run: print("this is running on self hosted runner with label of ubuntu-focal")
        shell: python3